/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'Introduction',
    'Installation',
    'Getting Started',
    {
      type: 'category',
      label: 'Interfaces',
      items: [
        'interface/ButtonOptions',
        'interface/CanvasOptions',
        'interface/CircleOptions',
        'interface/DrawTextOptions',
        'interface/Drawable',
        'interface/InputFieldOptions',
        'interface/LineOptions',
        'interface/PointOptions',
        'interface/RectangleOptions',
        'interface/Scene',
        'interface/Updatable',
      ],
    },
    {
      type: 'category',
      label: 'Types',
      items: ['type/AssetType', 'type/DrawFunction', 'type/UpdateFunction'],
    },
    {
      type: 'category',
      label: 'Enums',
      items: [
        'enum/ClickableState',
        'enum/InputFieldType',
        'enum/KeyState',
        'enum/MouseButton',
        'enum/NineSliceMode',
        'enum/SoundState',
        'enum/TouchState',
      ],
    },
    {
      type: 'category',
      label: 'Classes',
      items: [
        'class/Game',
        'class/GameCanvas',
        'class/GameLoop',
        'class/SceneManager',
        'class/ServiceContainer',
        {
          type: 'category',
          label: 'Assets',
          items: [
            'class/assets/AssetStore',
            'class/assets/Sound',
            'class/assets/Sprite',
            'class/assets/SpriteSheet',
            'class/assets/SpriteSheetAnimation',
            'class/assets/TileSet',
          ],
        },
        {
          type: 'category',
          label: 'Inputs',
          items: [
            'class/inputs/Keyboard',
            'class/inputs/Mouse',
            'class/inputs/Touch',
          ],
        },
        {
          type: 'category',
          label: 'Primitives',
          items: [
            'class/primitives/Circle',
            'class/primitives/Line',
            'class/primitives/Point',
            'class/primitives/Rectangle',
          ],
        },
        {
          type: 'category',
          label: 'UI',
          items: [
            'class/ui/Button',
            'class/ui/Clickable',
            'class/ui/InputField',
            'class/ui/NineSlice',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      items: ['functions/drawText'],
    },
  ],
};

module.exports = sidebars;
